name: release

on: [push, pull_request]

env:
  CI_MAKE: make -f .travis.mk

jobs:
  release:
    # We want to run on external PRs, but not on our own internal PRs
    # as they'll be run by the push to the branch.
    if: github.event_name == 'push' ||
        github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    # image built by .gitlab.mk instructions and targets from .travis.mk
    container:
      image: docker.io/tarantool/testing:debian-stretch
      # Our testing expects that the init process (PID 1) will
      # reap orphan processes. At least the following test leans
      # on it: app-tap/gh-4983-tnt-e-assert-false-hangs.test.lua.
      options: '--init'

    steps:
      # must be before the main job to get needed environment,
      # used to get CI_ACTION_REF_NAME value
      - uses: FranzDiebold/github-env-vars-action@v2.1.0
      - uses: actions/checkout@v1
      - name: test
        run: ALX ${CI_MAKE} test_debian_no_deps
      - name: call action with send Telegram message on failure
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_CORE_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_CORE_TO }}
        uses: ./.github/actions/send-telegram-notify
        if: failure()
      - name: artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: release
          retention-days: 21
          path: test/var/artifacts
