name: release_asan_clang11

on: [push, pull_request]

env:
  CI_MAKE: make -f .travis.mk

jobs:
  release_asan_clang11:
    # We want to run on external PRs, but not on our own internal PRs
    # as they'll be run by the push to the branch.
    if: github.event_name == 'push' ||
        github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    # image built by .gitlab.mk instructions and targets from .travis.mk
    container: docker.io/tarantool/testing:debian-buster

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: test
        run: ${CI_MAKE} test_asan_debian_no_deps
      - name: artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: release_asan_clang11
          retention-days: 1000000
          path: test/var/artifacts
